### ISSUE TITLE
युवन् सम्प्रसारणम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#101]
युवन् शब्दस्य पुनः सम्पर्सारणकर्तव्ये निषेधः न सम्प्रसारणे सम्प्रसारणमिति सूत्रेण। तत्र यकारस्य श्वयुवमघोनामतद्धिते इति सूत्रेण सम्प्रसारणे प्राप्ते न सम्प्रसारणे सम्प्रसारणमिति सूत्रेण निषेधः इति निषेधः दर्शनीयः।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/8147657/21f8095e-1294-11e5-801f-7bbf74d482a8.PNG)

It already shows the sUtra
