### ISSUE TITLE
अर्वन् जस् / अम् / औौट् 

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#102]
अर्वन् शब्दात् जस्, अम् औट् प्रत्ययेषु परेषु तृ आदेशस्य उगित्वात् उगिदचां सर्वनामस्थाने चाधातोः इति नुमागमः। रूपाणि अर्वन्तः, अर्वन्तम्, अर्वन्तौ इति भवेयुः।

**Comment by drdhaval2785** [comment]
$num=array(); at the end of the code solved the problem.
