### ISSUE TITLE
पञ्चन् सु

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#103]
पञ्चन् शब्दस्य प्रथमाविभक्त्येकवचनरूपमपि दर्शयति।

You entered: पञ्चन् + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :
1 - पञ्चन्+सुँ
dvyekayordvivacanaikavacane (1.4.22) :
द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :
1 - पञ्चन्+सुँ
By suDanapuMsakasya (1.1.43) :
सुडनपुंसकस्य (१.१.४३) :
1 - पञ्चन्+सुँ
By SNAntA Sat (1.1.24) :
ष्णान्ता षट्‌ (१.१.२४) :
1 - पञ्चन्+सुँ
asmad, yuSmad and words having SaT saJjJA have same forms in all three genders.
अस्मद्युष्मद्‍षट्सञ्ज्ञकाः त्रिषु सरूपाः ।
1 - पञ्चन्+सुँ
By na SaTsvasrAdibhyaH (4.1.10) :
न षट्स्वस्रादिभ्यः (४.१.१०) :
GIp mandated by Rnnebhyo GIp is overruled by this rule. :
न षट्स्वस्रादिभ्यः (४.१.१०) इत्यनेन ऋन्नेभ्यो ङीबित्यन्तेन प्राप्तो ङीब्निषिध्यते । :
1 - पञ्चन्+सुँ
By sarvanAmasthAne cAsambuddhau (6.4.8) :
सर्वनामस्थाने चासम्बुद्धौ (६.४.८) :
alo'ntyAtpUrva upadhA (1.1.65)
अलोऽन्त्यात्पूर्व उपधा (१.१.६५)
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - पञ्चान्+सुँ
000
By upadeze'janunAsika it (1.3.2) :
उपदेशेऽजनुनासिक इत्‌ (१.३.२) :
1 - पञ्चान्+सुँ
By tasya lopaH (1.3.9) :
तस्य लोपः (१.३.९) :
1 - पञ्चान्+स्
By na vibhaktau tusmAH (1.3.4) :
न विभक्तौ तुस्माः (१.३.४) :
1 - पञ्चान्+स्
By apRkta ekAlpratyayaH (1.2.41) :
अपृक्त एकाल्प्रत्ययः (१.२.४१) :
1 - पञ्चान्+स्
By halGyAbbhyo dIrghAtsutisyapRktaM hal (6.1.68) :
हल्ङ्‍याब्भ्यो दीर्घात्सुतिस्यपृक्तं हल्‌ (६.१.६८) :
1 - पञ्चान्+
By na lopaH prAtipadikAntasya (8.2.7) :
न लोपः प्रातिपदिकान्तस्य (८.२.७) :
1 - पञ्चा+
By nalopaH supsvarasaJjJAtugvidhiSu kRti (8.2.2) :
नलोपः सुप्स्वरसञ्ज्ञातुग्विधिषु कृति (८.२.२) :
1 - पञ्चा+
By anaci ca (8.4.47):
अनचि च (८.४.४७):
Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)
द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।
1 - पञ्चा
2 - पञ्ञ्चा
N.B.: By triprabhRtiSu zAkaTAyanasya (8.4.50), the dvitva is optionally not done in cases where there are more than three hals appearing consecutively. e.g. indra - inndra.
त्रिप्रभृतिषु शाकटायनस्य (८.४.५०) - तीन या उससे ज्यादा हल्‌ अगर हो तब शाकटायन के मत में द्वित्व नहीं होता है ।
By aNo'pragRhyasyAnunAsikaH (8.4.57) :
अणोऽप्रगृह्यस्यानुनासिकः (८.३.५७) :
1 - पञ्चा
2 - पञ्चाँ
3 - पञ्ञ्चा
4 - पञ्ञ्चाँ
Final forms are :
आखिरी रूप हैं :
1 - पञ्चा
2 - पञ्चाँ
3 - पञ्ञ्चा
4 - पञ्ञ्चाँ

**Comment by drdhaval2785** [comment]
This is already corrected. Only when the saJjJA / upasarjanIbhUta option is selected, then this derivation comes.
