### ISSUE TITLE
पञ्चन् जस्, शस्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#105]
पञ्चन् शब्दात् जसि, शसि च नलोपः सुप्स्वर.... इत्याि सूत्रस्य आवश्यकता नास्ति।

By nalopaH supsvarasaJjJAtugvidhiSu kRti (8.2.2) :
नलोपः सुप्स्वरसञ्ज्ञातुग्विधिषु कृति (८.२.२) :
1 - पञ्च+

**Comment by drdhaval2785** [comment]
Already tackled earlier
