### ISSUE TITLE
अष्टन् जस्, शस्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#107]
अष्टाभ्य औश् इति सूत्रेण औश् आदेशः भवेत् जस् प्रत्यये, शस् प्रत्यये च परे।
You entered: अष्टन् + जस् Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :
1 - अष्टन्+जस्
bahuSu bahuvacanam (1.4.21) :
बहुषु बहुवचनम्‌ (१.४.२१) :
1 - अष्टन्+जस्
sarUpANAmekazeSa ekavibhaktau (1.2.64) :
सरूपाणामेकशेष एकविभक्तौ (१.२.६४) :
1 - अष्टन्+जस्
By suDanapuMsakasya (1.1.43) :
सुडनपुंसकस्य (१.१.४३) :
1 - अष्टन्+जस्
By SNAntA Sat (1.1.24) :
ष्णान्ता षट्‌ (१.१.२४) :
1 - अष्टन्+जस्
asmad, yuSmad and words having SaT saJjJA have same forms in all three genders.
अस्मद्युष्मद्‍षट्सञ्ज्ञकाः त्रिषु सरूपाः ।
1 - अष्टन्+जस्
By na SaTsvasrAdibhyaH (4.1.10) :
न षट्स्वस्रादिभ्यः (४.१.१०) :
GIp mandated by Rnnebhyo GIp is overruled by this rule. :
न षट्स्वस्रादिभ्यः (४.१.१०) इत्यनेन ऋन्नेभ्यो ङीबित्यन्तेन प्राप्तो ङीब्निषिध्यते । :
1 - अष्टन्+जस्
By SaDbhyo luk (7.1.22) :
षड्भ्यो लुक्‌ (७.१.२२) :
pratyayasya lukzlulupaH (1.1.61)
प्रत्ययस्य लुक्श्लुलुपः (१.१.६१)
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - अष्टन्+
pratyayalope pratyayalakSaNam (1.1.62) is overridden by na lumatAGgasya (1.1.63) :
प्रत्ययलोपे प्रत्ययलक्षणम्‌ (१.१.६२) का न लुमताङ्गस्य (१.१.६३) से बाध हुआ है । :
1 - अष्टन्+
000
By na lopaH prAtipadikAntasya (8.2.7) :
न लोपः प्रातिपदिकान्तस्य (८.२.७) :
1 - अष्ट+
By nalopaH supsvarasaJjJAtugvidhiSu kRti (8.2.2) :
नलोपः सुप्स्वरसञ्ज्ञातुग्विधिषु कृति (८.२.२) :
1 - अष्ट+
By anaci ca (8.4.47):
अनचि च (८.४.४७):
Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)
द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।
1 - अष्ट
2 - अष्ष्ट
zaraH khayaH (vA 5019) :
शरः खयः (वा ५०१९) :
Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)
द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।
1 - अष्ट
2 - अष्ट्ट
3 - अष्ष्ट
4 - अष्ष्ट्ट
N.B.: By triprabhRtiSu zAkaTAyanasya (8.4.50), the dvitva is optionally not done in cases where there are more than three hals appearing consecutively. e.g. indra - inndra.
त्रिप्रभृतिषु शाकटायनस्य (८.४.५०) - तीन या उससे ज्यादा हल्‌ अगर हो तब शाकटायन के मत में द्वित्व नहीं होता है ।
By khari ca (8.4.55) :
N.B. By khari ca (8.4.55), 'car' varNas give 'car' varNas only as their savarNa :
खरि च (८.४.५५) :
खरि च (८.४.५५) से चर्‌ वर्णों का सवर्ण चर्‌ ही रहता है ।
1 - अष्ट
2 - अष्ट्ट
3 - अष्ष्ट
4 - अष्ष्ट्ट
By aNo'pragRhyasyAnunAsikaH (8.4.57) :
अणोऽप्रगृह्यस्यानुनासिकः (८.३.५७) :
1 - अष्टँ
2 - अष्ट
3 - अष्ट्टँ
4 - अष्ट्ट
5 - अष्ष्टँ
6 - अष्ष्ट
7 - अष्ष्ट्टँ
8 - अष्ष्ट्ट
By jharo jhari savarNe (8.4.65) :
झरो झरि सवर्णे (८.४.६५) :
1 - अष्टँ
2 - अष्ट
3 - अष्ट्टँ
4 - अष्ट्ट
5 - अष्ष्टँ
6 - अष्ष्ट
7 - अष्ष्ट्टँ
8 - अष्ष्ट्ट
Final forms are :
आखिरी रूप हैं :
1 - अष्टँ
2 - अष्ट
3 - अष्ट्टँ
4 - अष्ट्ट
5 - अष्ष्टँ
6 - अष्ष्ट
7 - अष्ष्ट्टँ
8 - अष्ष्ट्ट
You entered: अष्टन् + शस् Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :
1 - अष्टन्+शस्
bahuSu bahuvacanam (1.4.21) :
बहुषु बहुवचनम्‌ (१.४.२१) :
1 - अष्टन्+शस्
sarUpANAmekazeSa ekavibhaktau (1.2.64) :
सरूपाणामेकशेष एकविभक्तौ (१.२.६४) :
1 - अष्टन्+शस्
By SNAntA Sat (1.1.24) :
ष्णान्ता षट्‌ (१.१.२४) :
1 - अष्टन्+शस्
asmad, yuSmad and words having SaT saJjJA have same forms in all three genders.
अस्मद्युष्मद्‍षट्सञ्ज्ञकाः त्रिषु सरूपाः ।
1 - अष्टन्+शस्
By na SaTsvasrAdibhyaH (4.1.10) :
न षट्स्वस्रादिभ्यः (४.१.१०) :
GIp mandated by Rnnebhyo GIp is overruled by this rule. :
न षट्स्वस्रादिभ्यः (४.१.१०) इत्यनेन ऋन्नेभ्यो ङीबित्यन्तेन प्राप्तो ङीब्निषिध्यते । :
1 - अष्टन्+शस्
By SaDbhyo luk (7.1.22) :
षड्भ्यो लुक्‌ (७.१.२२) :
pratyayasya lukzlulupaH (1.1.61)
प्रत्ययस्य लुक्श्लुलुपः (१.१.६१)
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - अष्टन्+
pratyayalope pratyayalakSaNam (1.1.62) is overridden by na lumatAGgasya (1.1.63) :
प्रत्ययलोपे प्रत्ययलक्षणम्‌ (१.१.६२) का न लुमताङ्गस्य (१.१.६३) से बाध हुआ है । :
1 - अष्टन्+
By svAdiSvasarvanAmasthAne (1.4.17) :
स्वादिष्वसर्वनामस्थाने (१.४.१७) :
1 - अष्टन्+
000
By na lopaH prAtipadikAntasya (8.2.7) :
न लोपः प्रातिपदिकान्तस्य (८.२.७) :
1 - अष्ट+
By nalopaH supsvarasaJjJAtugvidhiSu kRti (8.2.2) :
नलोपः सुप्स्वरसञ्ज्ञातुग्विधिषु कृति (८.२.२) :
1 - अष्ट+
By anaci ca (8.4.47):
अनचि च (८.४.४७):
Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)
द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।
1 - अष्ट
2 - अष्ष्ट
zaraH khayaH (vA 5019) :
शरः खयः (वा ५०१९) :
Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)
द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।
1 - अष्ट
2 - अष्ट्ट
3 - अष्ष्ट
4 - अष्ष्ट्ट
N.B.: By triprabhRtiSu zAkaTAyanasya (8.4.50), the dvitva is optionally not done in cases where there are more than three hals appearing consecutively. e.g. indra - inndra.
त्रिप्रभृतिषु शाकटायनस्य (८.४.५०) - तीन या उससे ज्यादा हल्‌ अगर हो तब शाकटायन के मत में द्वित्व नहीं होता है ।
By khari ca (8.4.55) :
N.B. By khari ca (8.4.55), 'car' varNas give 'car' varNas only as their savarNa :
खरि च (८.४.५५) :
खरि च (८.४.५५) से चर्‌ वर्णों का सवर्ण चर्‌ ही रहता है ।
1 - अष्ट
2 - अष्ट्ट
3 - अष्ष्ट
4 - अष्ष्ट्ट
By aNo'pragRhyasyAnunAsikaH (8.4.57) :
अणोऽप्रगृह्यस्यानुनासिकः (८.३.५७) :
1 - अष्टँ
2 - अष्ट
3 - अष्ट्टँ
4 - अष्ट्ट
5 - अष्ष्टँ
6 - अष्ष्ट
7 - अष्ष्ट्टँ
8 - अष्ष्ट्ट
By jharo jhari savarNe (8.4.65) :
झरो झरि सवर्णे (८.४.६५) :
1 - अष्टँ
2 - अष्ट
3 - अष्ट्टँ
4 - अष्ट्ट
5 - अष्ष्टँ
6 - अष्ष्ट
7 - अष्ष्ट्टँ
8 - अष्ष्ट्ट
Final forms are :
आखिरी रूप हैं :
1 - अष्टँ
2 - अष्ट
3 - अष्ट्टँ
4 - अष्ट्ट
5 - अष्ष्टँ
6 - अष्ष्ट
7 - अष्ष्ट्टँ
8 - अष्ष्ट्ट

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/8149377/97e69a3c-12de-11e5-965c-b0342ae6eb43.PNG)

Seems an issue of wrong choice

**Comment by mrudani** [comment]
मया तु नहीं इति विकल्पः चितः। प्रधान इति चयनेन तथा आगतम्। नहीं इति कदा चेतव्यम् तर्हि। अप्रधाने उपसर्नीभूत इति, संज्ञायाम् संज्ञा या उपसर्जनीभूत इति, तदभावे नहीं इति, तर्हि प्रधाधनत्वमित्येवार्थः खलु।
