### ISSUE TITLE
उष्णिह्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#109]
उष्णिह् इति शबदस्य स्त्रीलिङ्गरूपाणि उष्णिक्-उष्णिग्, उष्णिहौ इत्यादि परमत्र टाप्प्रत्ययं कृत्वा रूपाणि साधयति।
You entered: उष्णिह् + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :
1 - उष्णिह्+सुँ
dvyekayordvivacanaikavacane (1.4.22) :
द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :
1 - उष्णिह्+सुँ
By suDanapuMsakasya (1.1.43) :
सुडनपुंसकस्य (१.१.४३) :
1 - उष्णिह्+सुँ
ajAdyataSTAp (4.1.4) :
अजाद्यतष्टाप्‌ (४.१.४) 1:
These are not ending with akAra. Therefore included in ajAdi class for TAp pratyaya.
अदन्तत्व नहीं होने के कारण टाप्‌ प्रत्यय के लिए समर्थ बनाने के लिए अजादि गण में इनका समावेश किया गया है ।
1 - उष्णिह्+टाप्+सुँ
TakAra and pakAra are 'it'. They are elided by cuTU(1.3.7), halantyam (1.3.3) and tasya lopaH (1.3.9) :

**Comment by drdhaval2785** [comment]
same as #110
