### ISSUE TITLE
चतुर् स्त्रीलिङ्गम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#111]
चतुर् शब्दस्य प्रथमैकवचनं दर्शयति 

You entered: चतुर् + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :
1 - चतुर्+सुँ
dvyekayordvivacanaikavacane (1.4.22) :
द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :
1 - चतुर्+सुँ
By suDanapuMsakasya (1.1.43) :
सुडनपुंसकस्य (१.१.४३) :
1 - चतुर्+सुँ
By tricaturoH striyAM tisRcatasR (7.2.99) :
त्रिचतुरोः स्त्रियां तिसृचतस्रू (७.२.९९) :
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - चतसृ+सुँ
By RduzanaspurudaMso'nehasAM ca (7.1.94) :
ऋदुशनस्पुरुदंसोऽनेहसां च (७.१.९४) :
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - चतसन्+सुँ
By upadeze'janunAsika it (1.3.2) :
उपदेशेऽजनुनासिक इत्‌ (१.३.२) :
1 - चतसन्+सुँ
By tasya lopaH (1.3.9) :
तस्य लोपः (१.३.९) :
1 - चतसन्+स्
By na vibhaktau tusmAH (1.3.4) :
न विभक्तौ तुस्माः (१.३.४) :
1 - चतसन्+स्
Array ( [0] => u )
By sarvanAmasthAne cAsambuddhau (6.4.8) :
सर्वनामस्थाने चासम्बुद्धौ (६.४.८) :
alo'ntyAtpUrva upadhA (1.1.65)
अलोऽन्त्यात्पूर्व उपधा (१.१.६५)
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - चतसान्+स्
By apRkta ekAlpratyayaH (1.2.41) :
अपृक्त एकाल्प्रत्ययः (१.२.४१) :
1 - चतसान्+स्
By halGyAbbhyo dIrghAtsutisyapRktaM hal (6.1.68) :
हल्ङ्‍याब्भ्यो दीर्घात्सुतिस्यपृक्तं हल्‌ (६.१.६८) :
1 - चतसान्+
Array ( [0] => catasAn+ )
By na lopaH prAtipadikAntasya (8.2.7) :
न लोपः प्रातिपदिकान्तस्य (८.२.७) :
1 - चतसा+
By aNo'pragRhyasyAnunAsikaH (8.4.57) :
अणोऽप्रगृह्यस्यानुनासिकः (८.३.५७) :
1 - चतसा
2 - चतसाँ
Final forms are :
आखिरी रूप हैं :
1 - चतसा
2 - चतसाँ

**Comment by drdhaval2785** [comment]
nahI, anya selection gives the correct forms.
