### ISSUE TITLE
चतुर् जस्,शस्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#112]
चतुर् शब्दात् जसि, शसि च यणादेशं  वदति बालमनोरमाकारः।

**Comment by drdhaval2785** [comment]
@mrudani 
अचि र ऋतः इत्यस्य प्रयोगविषय इति मन्ये ।

**Comment by mrudani** [comment]
बालमनोरमायाः प्रमादः इति वक्तुं शक्यते। अतः अचि र ऋतः इति एव।

**Comment by drdhaval2785** [comment]
So the machine is more faithful than Balamanorama. :)

**Comment by gasyoun** [comment]
It's where it get's scary.
