### ISSUE TITLE
वाच् स्त्रीलिङ्गरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#116]
वाच् इति शब्दात् कथं टाप्, कथमेवं रूपं च। वाग्-वाक्, वाचौ, वाचः इत्येवंरूपेण भवेयुः।

You entered: वाच् + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :
1 - वाच्+सुँ
dvyekayordvivacanaikavacane (1.4.22) :
द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :
1 - वाच्+सुँ
By suDanapuMsakasya (1.1.43) :
सुडनपुंसकस्य (१.१.४३) :
1 - वाच्+सुँ
ajAdyataSTAp (4.1.4) :
अजाद्यतष्टाप्‌ (४.१.४) 1:
These are not ending with akAra. Therefore included in ajAdi class for TAp pratyaya.
अदन्तत्व नहीं होने के कारण टाप्‌ प्रत्यय के लिए समर्थ बनाने के लिए अजादि गण में इनका समावेश किया गया है ।
1 - वाच्+टाप्+सुँ
TakAra and pakAra are 'it'. They are elided by cuTU(1.3.7), halantyam (1.3.3) and tasya lopaH (1.3.9) :
टपावितौ । चुटू (१.३.७), हलन्त्यम्‌ (१.३.३) और तस्य लोपः (१.३.९) :
1 - वाचा+सुँ
By upadeze'janunAsika it (1.3.2) :
उपदेशेऽजनुनासिक इत्‌ (१.३.२) :
1 - वाचा+सुँ
By tasya lopaH (1.3.9) :
तस्य लोपः (१.३.९) :
1 - वाचा+स्
By na vibhaktau tusmAH (1.3.4) :
न विभक्तौ तुस्माः (१.३.४) :
1 - वाचा+स्
Array ( [0] => p [1] => w [2] => u )
By apRkta ekAlpratyayaH (1.2.41) :
अपृक्त एकाल्प्रत्ययः (१.२.४१) :
1 - वाचा+स्
By halGyAbbhyo dIrghAtsutisyapRktaM hal (6.1.68) :
हल्ङ्‍याब्भ्यो दीर्घात्सुतिस्यपृक्तं हल्‌ (६.१.६८) :
1 - वाचा+
Array ( [0] => vAcA+ )
By aNo'pragRhyasyAnunAsikaH (8.4.57) :
अणोऽप्रगृह्यस्यानुनासिकः (८.३.५७) :
1 - वाचा
2 - वाचाँ
Final forms are :
आखिरी रूप हैं :
1 - वाचा
2 - वाचाँ

**Comment by drdhaval2785** [comment]
same as #118
