### ISSUE TITLE
अप् स्त्रीलिङ्गम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#117]
अप् शब्दस्य प्रथमैकवचने रूपं दर्शयति आपः इति। परन्तु प्रथमैकवचनरूपं न स्यात्।

You entered: अप् + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :
1 - अप्+सुँ
dvyekayordvivacanaikavacane (1.4.22) :
द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :
1 - अप्+सुँ
By suDanapuMsakasya (1.1.43) :
सुडनपुंसकस्य (१.१.४३) :
1 - अप्+सुँ
By aptRntRcsvasRnaptRneSTRtvaSTRkSattRhotRpotRprazAstRRNAm (6.4.11) :
अप्तृन्तृच्स्वसृनप्तृनेष्टृत्वष्टृक्षत्तृहोतृपोतृप्रशास्तॄणाम्‌ (६.४.११) :
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - आप्+सुँ
By upadeze'janunAsika it (1.3.2) :
उपदेशेऽजनुनासिक इत्‌ (१.३.२) :
1 - आप्+सुँ
By tasya lopaH (1.3.9) :
तस्य लोपः (१.३.९) :
1 - आप्+स्
By na vibhaktau tusmAH (1.3.4) :
न विभक्तौ तुस्माः (१.३.४) :
1 - आप्+स्
Array ( [0] => u )
By apRkta ekAlpratyayaH (1.2.41) :
अपृक्त एकाल्प्रत्ययः (१.२.४१) :
1 - आप्+स्
By halGyAbbhyo dIrghAtsutisyapRktaM hal (6.1.68) :
हल्ङ्‍याब्भ्यो दीर्घात्सुतिस्यपृक्तं हल्‌ (६.१.६८) :
1 - आप्+
Array ( [0] => Ap+ )
By jhalAM jazo'nte (8.2.39), The padAnta is 'jhal' is replaced by 'jaz' :
झलां जशोऽन्ते (८.२.३९) :
1 - आब्+
By anaci ca (8.4.47) and dIrghAdAcAryANAm (8.4.52) :
अनचि च (८.४.४७): तथा दीर्घादाचार्याणाम्‌ (८.४.५२) :
Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)
द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।
1 - आब्
2 - आब्ब्
By vA'vasAne (8.4.54) :
वाऽवसाने (८.४.५४) :
1 - आब्
2 - आप्
3 - आब्ब्
4 - आब्प्
By khari ca (8.4.55) :
खरि च (८.४.५५) :
1 - आब्
2 - आप्
3 - आब्ब्
4 - आप्प्
By khari ca (8.4.55) :
N.B. By khari ca (8.4.55), 'car' varNas give 'car' varNas only as their savarNa :
खरि च (८.४.५५) :
खरि च (८.४.५५) से चर्‌ वर्णों का सवर्ण चर्‌ ही रहता है ।
1 - आब्
2 - आप्
3 - आब्ब्
4 - आप्प्
Final forms are :
आखिरी रूप हैं :
1 - आब्
2 - आप्
3 - आब्ब्
4 - आप्प्

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/8165662/f2d12fd0-13af-11e5-8f83-0053ab2f6f6b.PNG)

When I chose the abovementioned choice, there was no wrong form.

Only bahuvacanam happened
