### ISSUE TITLE
दृश् -स्त्रीलिङ्ग

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#119]
दृश् शब्दस्य स्त्रीलिङ्गरूपाणि दृक्-दृग्, दृशौ, दृशः इत्येेेवं भवेयुः। परमत्र दृशा, दृशे इत्येवं रीपेण दर्शयति।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/8165554/f0cd36da-13ae-11e5-95d4-dda00bde98d8.PNG)

गणरत्नमहोदधि says like this

**Comment by drdhaval2785** [comment]
But even then, this is an optional form.
Optional form is to be shown.
