### ISSUE TITLE
त्विष्,सजुष् स्त्रीलिङ्ग

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#120]
शब्दरीपाणि साधु आयान्ति। परम्
न विभक्तौ तुस्माः (१.३.४) :
1 - त्विष्+स्
Array ( [0] => u )

ससजुषो रुः (८.२.६६) :
1 - सजुरुँ+भ्याम्
Array ( [0] => sajur@+ByAm )

एवमायान्ति।

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritSubanta/commit/96be27f52d150b38ec5c3f24e3025067b447e617 closed it
