### ISSUE TITLE
आशिष् स्त्रीलिङ्ग

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#121]
tasya lopaH (1.3.9) :
तस्य लोपः (१.३.९) :
1 - आशिष्+आ
Array ( [0] => w ) Array ( [0] => ASiz+A )

दर्शने एवमायाति

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/SanskritSubanta/commit/96be27f52d150b38ec5c3f24e3025067b447e617 closed it
