### ISSUE TITLE
खञ्ज्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#123]
खञ्ज् शब्दः क्विप्प्रत्ययान्तः न तु क्विन्, तत्र क्विन् प्रत्ययान्त, नहीं इति विकल्पद्वयं दर्शयति। तत् परिवर्तनीयम्।

**Comment by drdhaval2785** [comment]
We don't want to know whether this is kvip or not.
It doesn't matter in derivation.

Only kvin matters.
So, you can select 'nahI'.
