### ISSUE TITLE
ऊर्ज्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#126]
rAtsasya (8.2.24) prevents application of saMyogAntasya lopaH.
रात्सस्य (८.२.२४) से संयोगान्तस्य लोपः का प्रतिषेध होता है ।
1 - ऊर्ज्+

रात्सस्य इत्यनेन नियमः क्रियते। न तु तत् सूत्रं बाधकम्।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/8212129/93df252a-1537-11e5-9719-5065431b678a.PNG)
