### ISSUE TITLE
अस्मद् पुंलिङ्ग

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#127]
अस्मद् शब्दस्य युष्मद् शब्द इव विकल्पाः नायान्ति। शब्दरूपाणि एवमायान्ति।

You entered: अ्स्मद् + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :
1 - अ्स्मद्+सुँ
dvyekayordvivacanaikavacane (1.4.22) :
द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :
1 - अ्स्मद्+सुँ
By suDanapuMsakasya (1.1.43) :
सुडनपुंसकस्य (१.१.४३) :
1 - अ्स्मद्+सुँ
By upadeze'janunAsika it (1.3.2) :
उपदेशेऽजनुनासिक इत्‌ (१.३.२) :
1 - अ्स्मद्+सुँ
By tasya lopaH (1.3.9) :
तस्य लोपः (१.३.९) :
1 - अ्स्मद्+स्
By na vibhaktau tusmAH (1.3.4) :
न विभक्तौ तुस्माः (१.३.४) :
1 - अ्स्मद्+स्
By apRkta ekAlpratyayaH (1.2.41) :
अपृक्त एकाल्प्रत्ययः (१.२.४१) :
1 - अ्स्मद्+स्
By halGyAbbhyo dIrghAtsutisyapRktaM hal (6.1.68) :
हल्ङ्‍याब्भ्यो दीर्घात्सुतिस्यपृक्तं हल्‌ (६.१.६८) :
1 - अ्स्मद्+
By jhalAM jazo'nte (8.2.39), The padAnta is 'jhal' is replaced by 'jaz' :
झलां जशोऽन्ते (८.२.३९) :
1 - अ्स्मद्+
By anaci ca (8.4.47):
अनचि च (८.४.४७):
Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)
द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।
1 - अ्स्मद्
2 - अ्स्मद्द्
By vA'vasAne (8.4.54) :
वाऽवसाने (८.४.५४) :
1 - अ्स्मद्
2 - अ्स्मत्
3 - अ्स्मद्द्
4 - अ्स्मद्त्
By khari ca (8.4.55) :
खरि च (८.४.५५) :
1 - अ्स्मद्
2 - अ्स्मत्
3 - अ्स्मद्द्
4 - अ्स्मत्त्
By khari ca (8.4.55) :
N.B. By khari ca (8.4.55), 'car' varNas give 'car' varNas only as their savarNa :
खरि च (८.४.५५) :
खरि च (८.४.५५) से चर्‌ वर्णों का सवर्ण चर्‌ ही रहता है ।
1 - अ्स्मद्
2 - अ्स्मत्
3 - अ्स्मद्द्
4 - अ्स्मत्त्
Final forms are :
आखिरी रूप हैं :
1 - अ्स्मद्
2 - अ्स्मत्
3 - अ्स्मद्द्
4 - अ्स्मत्त्

**Comment by drdhaval2785** [comment]
My machine gives the options.
Just refresh your browser by pressing F5
