### ISSUE TITLE
प्राञ्च्, प्रत्यञ्च्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#128]
प्राञ्च्-प्रत्यञ्चयोः परिक्षणाय प्रातिपदिकं प्राच् प्रत्यच् इति देयं खलु, तथा दत्ते सति अन्यदेव आयति। प्राञ्च् इति दत्ते सति 
एवमायाति - 

By ugidacAM sarvanAmasthAne'dhAtoH (7.1.70) :
उगिदचां सर्वनामस्थानेऽधातोः (७.१.७०) :
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - प्रान्ञ्च्+स्
By apRkta ekAlpratyayaH (1.2.41) :
अपृक्त एकाल्प्रत्ययः (१.२.४१) :
1 - प्रान्ञ्च्+स्
By halGyAbbhyo dIrghAtsutisyapRktaM hal (6.1.68) :
हल्ङ्‍याब्भ्यो दीर्घात्सुतिस्यपृक्तं हल्‌ (६.१.६८) :
1 - प्रान्ञ्च्+
By saMyogAntasya lopaH (8.2.23) and nimittApAye naimittikasyApyapAyaH (pa) :
संयोगान्तस्य लोपः (८.२.२३) तथा निमित्तापाये नैमित्तिकस्याप्यपायः (प) :
1 - प्रान्न्+
By kvinpratyayasya kuH (8.2.62) :
क्विन्प्रत्ययस्य कुः (८.२.६२) :
1 - प्रान्ङ्+
By aTkupvAGnumvyavAye'pi (8.4.2) :
अट्कुप्वाङ्नुम्व्यवायेऽपि (८.४.२) :
1 - प्राण्ङ्
Final forms are :
आखिरी रूप हैं :
1 - प्राण्ङ्

**Comment by drdhaval2785** [comment]
When I give prAYc and select 'anya'
I get the following.

![capture](https://cloud.githubusercontent.com/assets/5755132/8247207/d34f3b0e-1669-11e5-817c-28986329b489.PNG)
