### ISSUE TITLE
ददत् - तुदत् (न.पुं)

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#142]
ददत् शब्दस्य प्रथमैकवचने ददन् इति न भवेत्। सर्वनामस्थानसंज्ञा नपुंसकानां शि परे एव भवति। अतः प्रथमैकवचनस्य सर्वनामस्थानसंज्ञाभावात्, तन्निमित्तक नुमागमो न।
तुदत् शब्दस्यापि अभ्यस्तसंज्ञाकार्याणि एव दर्शयति। अस्य अभ्यस्तसंज्ञाभावात्, तन्निमित्तककार्याणि अस्य न स्युः।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/8272218/28c74d7a-1858-11e5-9ac2-664c24914c53.PNG)

dadat is already corrected.
tudat is not giving such results when I select the above options.
