### ISSUE TITLE
पयस् शी

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#146]
पयसी इति रूपं भवेत्। परन्तु
By napuMsakAcca (7.1.19) :
नपुंसकाच्च (७.१.१९) :
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - पयस्+शी
By lazakvataddhite (1.3.8) and tasya lopaH (1.1.9) :
लशक्वतद्धिते (१.३.८) तथा तस्य लोपः (१.१.९) :
1 - पयस्+ई
By auGaH zyAM pratiSedho vAcyaH (vA) :
This vArtika prevents application of 'yasyeti ca'.
औङः श्यां प्रतिषेधो वाच्यः (वा) :
'यस्येति च' इति सूत्रेण प्राप्तौ अकारेकारलोपौ अनेन वार्तिकेन निषिध्यते ।
1 - पयस्+ई
By sasajuSo ruH (8.2.66) :
ससजुषो रुः (८.२.६६) :
1 - पयरुँ+ई
By bhobhagoaghoapUrvasya yo'zi (8.3.17):
भोभगोअघोअपूर्वस्य योऽशि (८.३.१७) :
1 - पयय्+ई
By lopaH zAkalyasya (8.3.19) and vyorlaghuprayatnataraH zAkaTAyanasya (8.3.18) :
लोपः शाकल्यस्य (८.३.१९) तथा व्योर्लघुप्रयत्नः शाकटायनस्य (८.३.१८) :
1 - पयय्+ई
2 - पय +ई
By aNo'pragRhyasyAnunAsikaH (8.4.57) :
अणोऽप्रगृह्यस्यानुनासिकः (८.३.५७) :
1 - पयय् ई
2 - पयय् ईँ
3 - पय ई
4 - पय ईँ
Final forms are :
आखिरी रूप हैं :
1 - पयय् ई
2 - पयय् ईँ
3 - पय ई
4 - पय ईँ

**Comment by drdhaval2785** [comment]
Already done along with another issue
