### ISSUE TITLE
सुहिन्स्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#148]
सान्तमहतः संयोगस्य इति सूत्रं प्रतिपदिकेष्वेव न तु धातुषु। अतः सुहिन् इत्येव रूपम्।

By sAntamahataH saMyogasya (6.4.10) :
सान्तमहतः संयोगस्य (६.४.१०) :
alo'ntyAtpUrva upadhA (1.1.65)
अलोऽन्त्यात्पूर्व उपधा (१.१.६५)
1 - सुहीन्स्+स्
By apRkta ekAlpratyayaH (1.2.41) :
अपृक्त एकाल्प्रत्ययः (१.२.४१) :
1 - सुहीन्स्+स्

**Comment by drdhaval2785** [comment]
All corrections done till now are uploaded on live server.
@mrudani Now you can refresh the lanover.com site and it would give you correct output for all other than gavAnc word.
