### ISSUE TITLE
बहुयज्वन् स्त्रीलिङ्ग

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#150]
बहुयज्वन् शब्दात् अन उपधालोपिनो अन्यतरस्याम् इति सूत्रेण विकल्पेन ङीप् न भवति। यतो  हि अत्र उपधालोपस्य निषेधः वर्तते न संयोगाद्वमन्तात् इति सूत्रेण।
By ana upadhAlopino'nyatarasyAm (4.1.28) :
अन उपधालोपिनोऽन्यतरस्याम्‌ (४.१.२८) :
anupasarjanAt (4.1.14) :
अनुपसर्जनात्‌ (४.१.१४) :
1 - बहुयज्वन्+सुँ
2 - बहुयज्वा+सुँ
3 - बहुयज्व्न्+ङीप्+सुँ
GakAra and pakAra are 'it'. They are elided by lazakvataddhite (1.3.8), halantyam (1.3.3) and tasya lopaH (1.3.9) :

**Comment by drdhaval2785** [comment]
@mrudani 
न संयोगाद्वमन्तादिति 'अल्लोपोऽनः' इत्यस्य निषेधः ।
अल्लोपोऽनः भम्येव प्रवर्तते अर्थात्‌ शसादिष्वेव प्रवर्तते ।
अतः सर्वनामस्थानेषु तस्य प्रवृत्तिरेव नास्ति ।

![capture](https://cloud.githubusercontent.com/assets/5755132/8370688/199ed798-1be9-11e5-8f63-9f218bb37f64.PNG)

**Comment by mrudani** [comment]
सः विषयः न, अत्र  ङीप्प्रवृत्तिविषये अन उपधालोपिनोन्यतरस्यामित्यस्य प्रवृत्तिर्नभवतीति वक्तुं सः प्रसंगः उक्तः।
