### ISSUE TITLE
दोष- शब्दरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#20]
दोष इति वस्तुतः नपुंसकलिङ्गशब्दः इति सिद्धान्तकौमुदी, परन्तु पुंलिङ्गे अप्यस्तीति व्याख्याकाराः.
दोष् इति केचन वदन्ति. दोष इति केचन अकारान्तं वदन्ति. अतः शक्यते यदि उभयथा देयम्.

**Comment by drdhaval2785** [comment]
```
दोष इति वस्तुतः नपुंसकलिङ्गशब्दः इति सिद्धान्तकौमुदी, परन्तु पुंलिङ्गे अप्यस्तीति व्याख्याकाराः.
```
Both the forms are getting correct.
```
दोष् इति केचन वदन्ति. दोष इति केचन अकारान्तं वदन्ति. अतः शक्यते यदि उभयथा देयम्.
```
Both forms are happenning correct.
