### ISSUE TITLE
सखी - सम्बुद्धिः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#21]
सखी शब्दस्य सम्बोधनैकवचने सखे इति स्यात्, सखीः इति प्रक्रियाप्रदर्शिनी.

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/5876719/872fb548-a33f-11e4-93c9-dc06abe8c9fa.PNG)

![capture](https://cloud.githubusercontent.com/assets/5755132/5876728/9b3add38-a33f-11e4-9fb4-d799b3c82433.PNG)


Preliminary reading gives me 'he sakhIH'.

Double check and let me know with proper rules.

**Comment by mrudani** [comment]
दीर्घह्रस्वयोः भ्रमवशात् मया तथावादि. प्रक्रियाप्रदर्शिन्या साधु प्रादर्शि.
