### ISSUE TITLE
कति शब्दरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#22]
न षट्स्वस्रादिभ्यः इति सूत्रस्य प्रवृत्तिः न भवति.

**Comment by mrudani** [comment]
एषा समस्या तथैवास्ति, न षट्स्वस्रादिभ्यः इति सूत्रप्रवृत्तिः वारणीयः। एवमेवास्य शब्दस्य प्रथमैकवचनरूपं न भवेत् कतिः इति।

**Comment by drdhaval2785** [comment]
कथं न भवति?
डति च इति सूत्रेण षट्सङ्ज्ञा भवत्येव ।

**Comment by drdhaval2785** [comment]
प्रथमैकवचनं न दृश्यते ।

**Comment by mrudani** [comment]
स्त्रीप्रत्ययस्य प्राप्तेरेवाभावे तस्य निषेधस्य आवश्यकता नास्तीति चिन्तयामि। पश्यामि। प्रथमैकवचनमधुनापि कतिः इति दर्शयति।
You entered: कति + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - कति+सुँ

dvyekayordvivacanaikavacane (1.4.22) :

द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :

1 - कति+सुँ

By suDanapuMsakasya (1.1.43) :

सुडनपुंसकस्य (१.१.४३) :

1 - कति+सुँ

By bahuguNavatuDati saGkhyA (1.1.28) and Dati ca (1.1.25) :

बहुगुणवतुडति सङ्ख्या (१.१.२८) तथा डति च (१.१.२५) :

1 - कति+सुँ

asmad, yuSmad and words having SaT saJjJA have same forms in all three genders.

अस्मद्युष्मद्‍षट्सञ्ज्ञकाः त्रिषु सरूपाः ।

1 - कति+सुँ

By na SaTsvasrAdibhyaH (4.1.10) :

न षट्स्वस्रादिभ्यः (४.१.१०) :

1 - कति+सुँ

By zeSo ghyasakhi (1.4.7) :

शेषो घ्यसखि (१.४.७) :

1 - कति+सुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - कति+सुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - कति+स्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - कति+स्

By sasajuSo ruH (8.2.66) :

ससजुषो रुः (८.२.६६) :

1 - कति+रुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - कति+रुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - कति+र्

By kharavasAnayorvisarjanIyaH (8.3.15) :

खरवसानयोर्विसर्जनीयः (८.३.१५) :

1 - कति+ः

Final forms are :

आखिरी रूप हैं :
1 - कतिः

**Comment by drdhaval2785** [comment]
Can you post the options which you selected?
I see only kati in bahuvacana

**Comment by drdhaval2785** [comment]
Done
