### ISSUE TITLE
लिङ्गः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#25]
मनस् इति शब्दः नपुंसकलिङ्गे विद्यमानत्वात्, तस्य पुंलिङ्गे रूपाणि न प्रदर्शयेत्,  परमस्मिन् प्रदर्श्यमानानि सन्ति, तद्वारणोपायाः चिन्त्याः, अथवा कालान्तरे कर्तुं चिन्तितमिति मन्ये।

**Comment by drdhaval2785** [comment]
पुँल्लिंगविकल्पः चितः नपुंसकविकल्पो वा? यदि शब्दो  नपुंसकलिड़्ग एव विद्यते तर्हि पुँल्लिंगविकल्पो किमर्थं चितः तच्चिन्त्यम् ।

**Comment by mrudani** [comment]
यदि पुंलिंगः दीयते तर्हि औट्पुट् किं भवतीति द्रष्टुं तथा कृतम्।

**Comment by drdhaval2785** [comment]
कालान्तरे करिष्यावः

**Comment by drdhaval2785** [comment]
This will require teaching machine the pulliGga, strIliGga, napuMsakaliGga words i.e. whole dictionary.
It is not difficult.
I just have to feed the MW dictionary from Jim's site.
But, whether it would be useful or not is the question.
Let us wait for the time to mature
