### ISSUE TITLE
कतरशब्दरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#27]
You entered: कतर + जस् Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - कतर+जस्

bahuSu bahuvacanam (1.4.21) :

बहुषु बहुवचनम्‌ (१.४.२१) :

1 - कतर+जस्

sarUpANAmekazeSa ekavibhaktau (1.2.64) :

सरूपाणामेकशेष एकविभक्तौ (१.२.६४) :

1 - कतर+जस्

By suDanapuMsakasya (1.1.43) :

सुडनपुंसकस्य (१.१.४३) :

1 - कतर+जस्

By cuTU (1.3.7) :

चुटू (१.३.७) :

1 - कतर+जस्

tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - कतर+अस्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - कतर+अस्

ato guNe (6.1.96) is exception to only akaH savarNe dIrghaH (6.1.101) and not to prathamayoH pUrvasavarNaH (6.1.102), because of the paribhASA 'purastAdapavAdA anantarAnvidhInbAdhante nottarAn (pa 60). Therefore pURvasavarNadIrgha can occur. :

'पुरस्तादपवादा अनन्तरान्विधीन्बाधन्ते नोत्तरान्‌ (प ६०) परिभाषा के कारण अतो गुणे (६.१.९६) सिर्फ अकः सवर्णे दीर्घः (६.१.१०१) का अपवाद है, प्रथमयोः पूर्वसवर्णः (६.१.१०२) का नहीं । अतः पूर्वसवर्णदीर्घ हो सकता है ।

1 - कतर+अस्

By prathamayoH pUrvasavarNaH (6.1.102) :

N.B. : This applies to only in prathamA and dvitIyA vibhakti, and not in other cases.

प्रथमयोः पूर्वसवर्णः (६.१.१०२) :

यह प्रथमा और द्वितीया विभक्तियों में लागू होता है ।

1 - कतरा+स्

By sasajuSo ruH (8.2.66) :

ससजुषो रुः (८.२.६६) :

1 - कतरा+रुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - कतरा+रुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - कतरा+र्

By kharavasAnayorvisarjanIyaH (8.3.15) :

खरवसानयोर्विसर्जनीयः (८.३.१५) :

1 - कतरा+ः

Final forms are :

आखिरी रूप हैं :

1 - कतराः
इति आयाति। कतर शब्दस्य सर्वनामसंज्ञकत्वात् कतरे इति स्यात्।

**Comment by mrudani** [comment]
कतमशब्दरूपाणि अपि तथैव सन्ति।

**Comment by drdhaval2785** [comment]
It was because the options were not being displayed.
Now the options come properly.
This issue doesn't survive now.

```
You entered: कतर + जस् Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - कतर+जस्

bahuSu bahuvacanam (1.4.21) :

बहुषु बहुवचनम्‌ (१.४.२१) :

1 - कतर+जस्

sarUpANAmekazeSa ekavibhaktau (1.2.64) :

सरूपाणामेकशेष एकविभक्तौ (१.२.६४) :

1 - कतर+जस्

sarvAdIni sarvanAmAni (1.1.27) and tadantasyApIyaM saJjJA. dvandve ca iti jJApakAt :

सर्वादीनि सर्वनामानि (१.१.२७) तथा तदन्तस्यापीयं सञ्ज्ञा । द्वन्द्वे च इति ज्ञापकात्‌ :

1 - कतर+जस्

By suDanapuMsakasya (1.1.43) :

सुडनपुंसकस्य (१.१.४३) :

1 - कतर+जस्

By jasaH zI (7.1.17) :

जसः शी (७.१.१७) :

N.B. anekAlzitsarvasya mandates sarvAdeza :

अनेकाल्शित्सर्वस्य से सर्वादेश होता है । :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - कतर+शी

By lazakvataddhite (1.3.8) :

लशक्वतद्धिते (१.३.८) :

1 - कतर+शी

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - कतर+ई

By nAdici (6.1.104) :

N.B. : This is exception to prathamayoH pUrvasavarNaH.

नादिचि (६.१.१०४) :

यह नियम प्रथमयोः पूर्वसवर्णः का अपवाद है ।

1 - कतर+ई

By AdguNaH (6.1.87) :

आद्गुणः (६.१.८७) :

1 - कतर्+ए

Final forms are :

आखिरी रूप हैं :

1 - कतरे
```
