### ISSUE TITLE
उभयशब्दरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#28]
उभयशब्दस्य द्विवचनरूपाणि एव दत्तानि, परं तस्य शब्दस्य द्विवचनमेव नास्ति, उभयः- उभये, उभयम् - उभयान्, उभयेन - उभयैः, उभयस्मै - ऊभयेभ्यः, उभयस्मात् - उभयेभ्यः, उभयस्य - उभयेषाम्, उभयस्मिन् - उभयेषु, हे उभय - हे उभये

**Comment by drdhaval2785** [comment]
Which rule says so?

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/7206482/7434b766-e54f-11e4-92dc-a5fee09f9b11.PNG)

This says that generally ubhaya has singular and plural only.
Only Haradatta thinks that this word has dual also.
