### ISSUE TITLE
उभळब्दरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#29]
उभशब्दस्य प्रथमैकवचनमपि दर्शयति 
You entered: उभ + सुँ 

आखिरी रूप हैं :

1 - उभः
इति। परम् उभशब्दस्य पुंलिंग-एकवचनरूपं नास्ति।

**Comment by drdhaval2785** [comment]
As said before, it was about error in displaying options.
Now going perfect.
