### ISSUE TITLE
एकशब्दः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#33]
एक इति शब्दस्य संख्यावाचित्वे एकवचनरूपाणि एव स्युः, सः विभागः अपि दर्शनीयः।

**Comment by drdhaval2785** [comment]
संख्यावाचित्वे सति ङेप्रत्यये परे स्थिते एकाय भवेद्‌ एकस्मै वा ?
तथा स्थिते सर्वनामसञ्ज्ञा भवति वा न वा इति मम मनसि संशयः ।
समाधानं करोतु भवती ।
तदनन्तरं करोमि ।

**Comment by mrudani** [comment]
एकस्मै इत्येव भवति।
