### ISSUE TITLE
त्रि शब्दस्य रूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#34]
त्रिशब्दस्यापि प्रथमैकवचनरूपं दर्शयति। परं न भवेत्।
You entered: त्रि + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - त्रि+सुँ

dvyekayordvivacanaikavacane (1.4.22) :

द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :

1 - त्रि+सुँ

By suDanapuMsakasya (1.1.43) :

सुडनपुंसकस्य (१.१.४३) :

1 - त्रि+सुँ

By zeSo ghyasakhi (1.4.7) :

शेषो घ्यसखि (१.४.७) :

1 - त्रि+सुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - त्रि+सुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - त्रि+स्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - त्रि+स्

By sasajuSo ruH (8.2.66) :

ससजुषो रुः (८.२.६६) :

1 - त्रि+रुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - त्रि+रुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - त्रि+र्

By kharavasAnayorvisarjanIyaH (8.3.15) :

खरवसानयोर्विसर्जनीयः (८.३.१५) :

1 - त्रि+ः

Final forms are :

आखिरी रूप हैं :

1 - त्रिः

**Comment by drdhaval2785** [comment]
Choose the appropriate option.
My computer gives only bahuvacana forms
