### ISSUE TITLE
बहुश्रेयसी शब्दः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#35]
प्रकृतिः : बहुश्रेयसी
पुँल्लिङ्ग स्त्रीलिङ्ग नपुंसकलिङ्ग
Devanagari IAST SLP1
﻿
अनदीसञ्ज्ञकः अधातुः इति चिते सति
You entered: बहुश्रेयसी + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - बहुश्रेयसी+सुँ

dvyekayordvivacanaikavacane (1.4.22) :

द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :

1 - बहुश्रेयसी+सुँ

By suDanapuMsakasya (1.1.43) :

सुडनपुंसकस्य (१.१.४३) :

1 - बहुश्रेयसी+सुँ

By yU stryAkhyau nadI (1.4.3) and prathamaliGgagrahaNaJca (vA 1036) :

यू स्त्र्याख्यौ नदी (१.४.३) तथा प्रथमलिङ्गग्रहणञ्च (वा १०३६) :

1 - बहुश्रेयसी+सुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - बहुश्रेयसी+सुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - बहुश्रेयसी+स्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - बहुश्रेयसी+स्

By sasajuSo ruH (8.2.66) :

ससजुषो रुः (८.२.६६) :

1 - बहुश्रेयसी+रुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - बहुश्रेयसी+रुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - बहुश्रेयसी+र्

By kharavasAnayorvisarjanIyaH (8.3.15) :

खरवसानयोर्विसर्जनीयः (८.३.१५) :

1 - बहुश्रेयसी+ः

By anaci ca (8.4.47):

अनचि च (८.४.४७):

Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)

द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।

1 - बहुश्रेयसीः

2 - बहुश्श्रेयसीः

N.B.: By triprabhRtiSu zAkaTAyanasya (8.4.50), the dvitva is optionally not done in cases where there are more than three hals appearing consecutively. e.g. indra - inndra.

त्रिप्रभृतिषु शाकटायनस्य (८.४.५०) - तीन या उससे ज्यादा हल्‌ अगर हो तब शाकटायन के मत में द्वित्व नहीं होता है ।

By khari ca (8.4.55) :

N.B. By khari ca (8.4.55), 'car' varNas give 'car' varNas only as their savarNa :

खरि च (८.४.५५) :

खरि च (८.४.५५) से चर्‌ वर्णों का सवर्ण चर्‌ ही रहता है ।

1 - बहुश्रेयसीः

2 - बहुश्श्रेयसीः

Final forms are :

आखिरी रूप हैं :

1 - बहुश्रेयसीः

2 - बहुश्श्रेयसीः
इति आयाति।

**Comment by mrudani** [comment]
प्रकृतिः : बहुश्रेयसी
पुँल्लिङ्ग स्त्रीलिङ्ग नपुंसकलिङ्ग
Devanagari IAST SLP1
﻿
नदीसञ्ज्ञकः अधातुः
﻿
ङ्‍यन्त इति चिते सति 
You entered: बहुश्रेयसी + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - बहुश्रेयसी+सुँ

dvyekayordvivacanaikavacane (1.4.22) :

द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :

1 - बहुश्रेयसी+सुँ

By suDanapuMsakasya (1.1.43) :

सुडनपुंसकस्य (१.१.४३) :

1 - बहुश्रेयसी+सुँ

By yU stryAkhyau nadI (1.4.3) and prathamaliGgagrahaNaJca (vA 1036) :

यू स्त्र्याख्यौ नदी (१.४.३) तथा प्रथमलिङ्गग्रहणञ्च (वा १०३६) :

1 - बहुश्रेयसी+सुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - बहुश्रेयसी+सुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - बहुश्रेयसी+स्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - बहुश्रेयसी+स्

By apRkta ekAlpratyayaH (1.2.41) :

अपृक्त एकाल्प्रत्ययः (१.२.४१) :

1 - बहुश्रेयसी+स्

By halGyAbbhyo dIrghAtsutisyapRktaM hal (6.1.68) :

हल्ङ्‍याब्भ्यो दीर्घात्सुतिस्यपृक्तं हल्‌ (६.१.६८) :

1 - बहुश्रेयसी+

By anaci ca (8.4.47):

अनचि च (८.४.४७):

Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)

द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।

1 - बहुश्रेयसी

2 - बहुश्श्रेयसी

N.B.: By triprabhRtiSu zAkaTAyanasya (8.4.50), the dvitva is optionally not done in cases where there are more than three hals appearing consecutively. e.g. indra - inndra.

त्रिप्रभृतिषु शाकटायनस्य (८.४.५०) - तीन या उससे ज्यादा हल्‌ अगर हो तब शाकटायन के मत में द्वित्व नहीं होता है ।

By khari ca (8.4.55) :

N.B. By khari ca (8.4.55), 'car' varNas give 'car' varNas only as their savarNa :

खरि च (८.४.५५) :

खरि च (८.४.५५) से चर्‌ वर्णों का सवर्ण चर्‌ ही रहता है ।

1 - बहुश्रेयसी

2 - बहुश्श्रेयसी

By aNo'pragRhyasyAnunAsikaH (8.4.57) :

अणोऽप्रगृह्यस्यानुनासिकः (८.३.५७) :

1 - बहुश्रेयसी

2 - बहुश्रेयसीँ

3 - बहुश्श्रेयसी

4 - बहुश्श्रेयसीँ

Final forms are :

आखिरी रूप हैं :

1 - बहुश्रेयसी

2 - बहुश्रेयसीँ

3 - बहुश्श्रेयसी

4 - बहुश्श्रेयसीँ
इति आयाति।
अत्र बहुश्रेयसी शब्दः नदीसंज्ञकः नास्ति। अनदीसंज्ञकः अधातुः अस्ति, तस्य प्रथमैकवचनं रूपं भवति बहुश्रेयसी इति भवितव्यम्। परं बहुश्रेयसीः इति भवति। कथमेवम्।

**Comment by drdhaval2785** [comment]
```
प्रकृतिः : बहुश्रेयसी
पुँल्लिङ्ग स्त्रीलिङ्ग नपुंसकलिङ्ग
Devanagari IAST SLP1
﻿
अनदीसञ्ज्ञकः अधातुः इति चिते सति
```
In this first case you chose अनदीसञ्ज्ञकः अधातुः, which was wrong, because SK says that bahuSreyasI is nadI. 
You gave wrong input. So, you got बहुश्रेयसीः

```
रकृतिः : बहुश्रेयसी
पुँल्लिङ्ग स्त्रीलिङ्ग नपुंसकलिङ्ग
Devanagari IAST SLP1
﻿
नदीसञ्ज्ञकः अधातुः
﻿
ङ्‍यन्त इति चिते सति 
```
In the second case, you chose ङ्‍यन्त and नदी.
Therefore, halGyAbbhyo dIrghAt... applied and removed 's' from the end.
And therefore, बहुश्रेयसी was the output.

What was the fault?

**Comment by mrudani** [comment]
नदीसंज्ञाविधायकं वार्तिकं तत्र लेखनीयम् - प्रथमलिंगग्रहणं च इति।

**Comment by drdhaval2785** [comment]
It is already displayed.
Please look at 
```
By yU stryAkhyau nadI (1.4.3) and prathamaliGgagrahaNaJca (vA 1036) :

यू स्त्र्याख्यौ नदी (१.४.३) तथा प्रथमलिङ्गग्रहणञ्च (वा १०३६) :

1 - बहुश्रेयसी+सुँ
```

4th sUtra in the sequence you have copy pasted.
