### ISSUE TITLE
सुती शब्दरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#39]
सुती + अम् एरनेकाचो असंयोगपूर्वस्य इति यणादेशः। सुत्यम्
सुती + ङि एरनेकाचो असंयोगपूर्वस्य इति यणादेशः। सुत्यि

**Comment by drdhaval2785** [comment]
If the options are selected properly, the forms are created as suggested by you only.
![capture](https://cloud.githubusercontent.com/assets/5755132/7199536/3352ff14-e513-11e4-84c7-12bd27dc45bd.PNG)
