### ISSUE TITLE
लूनी शब्दरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#40]
लूनी शब्दात् ङसि प्रत्यये लूनी + अस् इति अवस्थायां नकारस्यासिद्धत्वात् तकार एव दृश्यते तेन ख्यत्यात्परस्य इति सूत्रस्य प्रवृत्तिः। लूनी + उस् लून्युः इति भवति।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/7199616/c4582ec6-e513-11e4-9023-c9658a13b5dd.PNG)
When correct options are chosen, the forms are good.

**Comment by mrudani** [comment]
तत्र विचारः न साधुरूपविषयकः, अपि तु तत्र कारणमुक्तम्, नकारासिद्धत्वम्, तत् तत्र लेखनीयमिति। तावदेव नान्यत्। तत्र आदौ ममोक्तिषु भावः अस्पष्टस्सयात्।
