### ISSUE TITLE
खलपू इत्यादयः शब्दाः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#42]
You entered: खलपू + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - खलपू+सुँ

dvyekayordvivacanaikavacane (1.4.22) :

द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :

1 - खलपू+सुँ

By kRdatiG (3.1.93) :

कृदतिङ्‌ (३.१.९३) :

1 - खलपू+सुँ

By suDanapuMsakasya (1.1.43) :

सुडनपुंसकस्य (१.१.४३) :

1 - खलपू+सुँ
Array ( [0] => KalapU+su! ) Array ( [0] => su! [1] => O [2] => jas [3] => am [4] => Ow [5] => Si ) 1pratyaya0

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - खलपू+सुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - खलपू+स्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - खलपू+स्
Array ( [0] => KalapU+s )

By sasajuSo ruH (8.2.66) :

ससजुषो रुः (८.२.६६) :

1 - खलपू+रुँ
Array ( [0] => KalapU+r@ )

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - खलपू+रुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - खलपू+र्

By kharavasAnayorvisarjanIyaH (8.3.15) :

खरवसानयोर्विसर्जनीयः (८.३.१५) :

1 - खलपू+ः

Final forms are :

आखिरी रूप हैं :

1 - खलपूः

Array ( [0] => KalapU+su! ) Array ( [0] => su! [1] => O [2] => jas [3] => am [4] => Ow [5] => Si ) 1pratyaya0

Array ( [0] => KalapU+s )

एवमायाति मध्ये किमर्थम्।

**Comment by drdhaval2785** [comment]
It was for testing. It got uploaded erraneously.
Uploading the correct file.
Treat this closed.
You won't see those words now.
