### ISSUE TITLE
प्रियत्रि + आम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#47]
अस्य साधनप्रक्रिया भिन्ना। अजाद्यतष्टाप् इति दर्शयति, तन्न भवेत्। 
By ajAdyataSTAp (4.1.4) :

अजाद्यतष्टाप्‌ (४.१.४) 3:

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - प्रियत्रया+आम्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - प्रियत्रया+आम्

By hrasvanadyApo nuT (7.1.54) :

ह्रस्वनद्यापो नुट्‌ (७.१.५४) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - प्रियत्रया+आम्

By hrasvanadyApo nuT (7.1.54) :

ह्रस्वनद्यापो नुट्‌ (७.१.५४) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - प्रियत्रया+नाम्

By nAmi (6.4.3) :

नामि (६.४.३) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - प्रियत्रया+नाम्

**Comment by drdhaval2785** [comment]
I chose the pulliGga one.
The output is as follows

```
You entered: प्रियत्रि + आम् Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - प्रियत्रि+आम्

bahuSu bahuvacanam (1.4.21) :

बहुषु बहुवचनम्‌ (१.४.२१) :

1 - प्रियत्रि+आम्

sarUpANAmekazeSa ekavibhaktau (1.2.64) :

सरूपाणामेकशेष एकविभक्तौ (१.२.६४) :

1 - प्रियत्रि+आम्

By zeSo ghyasakhi (1.4.7) :

शेषो घ्यसखि (१.४.७) :

1 - प्रियत्रि+आम्

By yaci bham (1.4.14) and A kaDArAdekA saJjJA (1.4.1) :

यचि भम्‌ (१.४.१४) तथा आ कडारादेका सञ्ज्ञा (१.४.१) :

1 - प्रियत्रि+आम्

By trestrayaH (7.1.53) :

त्रेस्त्रयः (७.१.५३) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - प्रियत्रय+आम्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - प्रियत्रय+आम्

By hrasvanadyApo nuT (7.1.54) :

ह्रस्वनद्यापो नुट्‌ (७.१.५४) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - प्रियत्रय+नाम्

Even though, supi ca (7.3.102) is a parasUtra, it doesn't operate here. The causes are: (1) violation of sannipAtaparibhASA and (2) ArambhasAmarthya of 'nAmi'. :

यद्यपि सुपि च (७.३.१०२) परसूत्र है, फिर भी उसकी प्रवृत्ति यहाँ नहीं होती है । सन्निपातपरिभाषा के विरोध से और नामि च सूत्र के प्रारम्भ के सामर्थ्य से ।

1 - प्रियत्रय+नाम्

By nAmi (6.4.3) :

नामि (६.४.३) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - प्रियत्रया+नाम्

By aTkupvAGnumvyavAye'pi (8.4.2) :

अट्कुप्वाङ्नुम्व्यवायेऽपि (८.४.२) :

1 - प्रियत्रयाणाम्
```

**Comment by drdhaval2785** [comment]
If the 'tri' word is not in strIliGga, it gives this priyatrayANAm (ajAdyataSTAp) derivation.
If the 'tri' word is in strIliGga, it gives priyatisRNAm derivation.
Correct me if I am wrong

**Comment by mrudani** [comment]
1. प्रक्रियायां अजाद्यतष्टाप् इति टाप् दर्शयति। तन्न भवेत्।
2. ह्रस्वनद्यापो नुट् इति नुट् आगमं दर्शयति। प्रियत्रया + नाम् अत्र ह्रस्वान्ताभावे कथं तस्य प्रवृत्तिः। अतः टाप् अकृत्वा नुट् आगमः करणीयः।
