### ISSUE TITLE
द्विशब्दरूपाणि स्त्रीलिङ्गे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#48]
द्विशब्दस्य स्तरीलिङ्गरूपेषु प्रथमैकवचनरूपं नागच्छेत्।
You entered: द्वि + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - द्वि+सुँ

dvyekayordvivacanaikavacane (1.4.22) :

द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :

1 - द्वि+सुँ

By suDanapuMsakasya (1.1.43) :

सुडनपुंसकस्य (१.१.४३) :

1 - द्वि+सुँ

By zeSo ghyasakhi (1.4.7) :

शेषो घ्यसखि (१.४.७) :

1 - द्वि+सुँ

By tyadAdInAmaH (7.2.102) :

Only the words till 'dvi' are included. (vA 4468) :

त्यदादीनामः (७.२.१०२) :

द्विपर्यन्तानामेवेष्टिः (वा ४४६८) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - द्व्+अ+सुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - द्व्+अ+सुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - द्व्+अ+स्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - द्व्+अ+स्

By sasajuSo ruH (8.2.66) :

ससजुषो रुः (८.२.६६) :

1 - द्व्+अ+रुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - द्व्+अ+रुँ

By tasya lopaH (1.3.9) :

द्विशब्दस्य स्त्रीलिङ्गरूपेषु प्रथमैकवचनरूपं नागच्छेत्।
तस्य लोपः (१.३.९) :

1 - द्व्+अ+र्

By kharavasAnayorvisarjanIyaH (8.3.15) :

खरवसानयोर्विसर्जनीयः (८.३.१५) :

1 - द्व्+अ+ः

Final forms are :

आखिरी रूप हैं :

1 - द्वः

**Comment by drdhaval2785** [comment]
When I chose 
![capture](https://cloud.githubusercontent.com/assets/5755132/7717414/ac02c8d0-febe-11e4-9a15-155843441f96.PNG)
the output is only dvivacanam

When I chose
![capture](https://cloud.githubusercontent.com/assets/5755132/7717419/c4f5f664-febe-11e4-8faf-3f344b3b4096.PNG)
The output has ekavacanam, because it is used for someone whose name is 'dvi'.
