### ISSUE TITLE
अतिस्त्रि + औ

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#50]
- अतिस्त्रि+औ

By iko'ci vibhaktau (7.1.73) :

इकोऽचि विभक्तौ (७.१.७३) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - अतिस्त्रिन्+औ

By napuMsakAcca (7.1.19) :

नपुंसकाच्च (७.१.१९) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - अतिस्त्रिन्+शी

अस्यां प्रक्रियायां विषयद्वयं वर्तते - 
1. अतिस्त्रि + औ इति दशायामादौ नपुंसकाच्च इति सूत्रेण औ-प्रत्ययस्य शी-आदेशः भवति। अतिस्त्रि + शि इति।
2. अतिस्त्रि + शी - इतिसंज्ञालोपानन्तरं - अतिस्त्रि + ई इति दशायां स्त्रियाः इति सूत्रेण प्राप्यमाणम्-इयङं प्रबाध्य इकः अचि विभक्तौ इति नुमागमः भवति इति बाध्यबाधकभावः दर्शनीयः।

**Comment by drdhaval2785** [comment]
```
By napuMsakAcca (7.1.19) :

नपुंसकाच्च (७.१.१९) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - अतिस्त्रि+शी

By lazakvataddhite (1.3.8) and tasya lopaH (1.1.9) :

लशक्वतद्धिते (१.३.८) तथा तस्य लोपः (१.१.९) :

1 - अतिस्त्रि+ई

By iko'ci vibhaktau (7.1.73) :

This rule overrules the possibility of 'iyaG' or 'uvaG'

इकोऽचि विभक्तौ (७.१.७३) :

इयङुवङौ प्रबाध्य इकोऽचि विभक्तौ (७.१.७३) इति नुमागमः भवति :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - अतिस्त्रिन्+ई
```
