### ISSUE TITLE
प्रधी + ङे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#52]
प्रकृष्टा धीः इति विग्रहे चिते सति, तस्य प्रक्रियायां नदीसंज्ञानिषेधः दृश्यते, परं ङितिह्रस्वश्च इति सूत्रेण विकल्पेण नहीसंज्ञा भवति एव।
By neyaGuvaGsthAnAvastrI (1.4.4) :

नेयङुवङ्स्थानावस्त्री (१.४.४) :

1 - प्रधी+ङे

**Comment by mrudani** [comment]
प्रध्यायतीत्यर्थे 
By yaci bham (1.4.14) and A kaDArAdekA saJjJA (1.4.1) :

यचि भम्‌ (१.४.१४) तथा आ कडारादेका सञ्ज्ञा (१.४.१) :

1 - प्रधी+ङे

By ANnadyAH (7.3.112) :

आण्नद्याः (७.३.११२) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - प्रधी+ङे

2 - प्रधी+आ+ङे
अत्र नदीसंज्ञाविधानसूत्रं दर्शनीयम्, ङितिह्रस्वश्चेति।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/7775829/1e78d2b2-00d4-11e5-9eec-54a739222354.PNG)
This is the output required for prakRSTA dhIryasya sA.
Corrected.

**Comment by drdhaval2785** [comment]
```
प्रध्यायतीत्यर्थे 
अत्र नदीसंज्ञाविधानसूत्रं दर्शनीयम्, ङितिह्रस्वश्चेति।
```

This is shown as follows
```
This word is declined like 'lakSmI' according to vRttikAra, and like its musculine counterpart according to kaiyaTa.

प्रधीशब्दस्य तु वृत्तिकारानां मते लक्ष्मीवद्रूपम्‌ । कैयटमते तु पुंवद्रूपम्‌ । :

1 - प्रधी+ङे
```

**Comment by drdhaval2785** [comment]
@mrudani 
Please check whether the explanation is proper or not.
