### ISSUE TITLE
खलपू - स्त्रीलिङ्गे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#55]
खलपवनस्य उत्सर्गतः पपंधर्मतया पदान्तरं विना स्त्रियां वर्तमानत्वाभावेन नित्यस्त्रीत्वाभावात् नदीत्वं नेति भावः इति बालमनोरमाव्याख्या। अतः अस्य नदीसंज्ञा नास्ति। परन्तु प्रक्रियाप्रदर्शिन्यां नदीसंज्ञानिषेधमेवं दर्शयति -
By neyaGuvaGsthAnAvastrI (1.4.4) :

नेयङुवङ्स्थानावस्त्री (१.४.४) :

1 - खलपू+सुँ
इति। एतद्द्रष्टव्यम्।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/7776466/e260ba74-00d8-11e5-89fc-216a970aae0d.PNG)

Done
