### ISSUE TITLE
ज्ञानशब्दरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#59]
You entered: ज्ञान + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - ज्ञान+सुँ

dvyekayordvivacanaikavacane (1.4.22) :

द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :

1 - ज्ञान+सुँ

By hrasvo napuMsake prAtipadikasya (1.2.47) :

ह्रस्वो नपुंसके प्रातिपदिकस्य (१.२.४७) :

1 - ज्ञान+सुँ

अस्यां प्रक्रियायां ह्रस्वोनपुंसके प्रातिपदिकस्य इति सूत्रस्य का आवश्यकता।

**Comment by drdhaval2785** [comment]
```
अस्यां प्रक्रियायां ह्रस्वोनपुंसके प्रातिपदिकस्य इति सूत्रस्य का आवश्यकता।
```
पर्जन्यवल्लक्षणप्रवृत्तिः

**Comment by mrudani** [comment]
अत्र प्राप्तिरेव नास्ति ।
