### ISSUE TITLE
ह्रस्वान्तानां प्रातिपदिकानां नपुंसकलिङ्गरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#64]
ह्रस्वान्तानां प्रातिपदिकानां प्रक्रियायां ह्रस्वो नपुंसके प्रातिपदिकस्य इति सूत्रस्यावश्यकता नास्ति।

**Comment by drdhaval2785** [comment]
parjanyavallakSaNapravRttiH
