### ISSUE TITLE
वारि + आम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#65]
'num' of 'iko'ci vibhaktau' is barred by 'nut' because of 'numaciratRjvadbhAvebhyo nuT pURvavipratiSedhena (vA 4374).

इकोऽचि विभक्तौ से प्राप्त नुमागम का 'नुमचिरतृज्वद्भावेभ्यो नुट्‌ पूर्वविप्रतिषेधेन (वा ४३७४) से बाध होता है ।

1 - वारि+आम्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - वारि+आम्

By hrasvanadyApo nuT (7.1.54) :

ह्रस्वनद्यापो नुट्‌ (७.१.५४) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - वारि+नाम्

अस्यां प्रक्रियायां न विभक्तौ तुस्माः इति आदौ प्रदर्श्य, अनन्तरं 
इकोऽचि विभक्तौ से प्राप्त नुमागम का 'नुमचिरतृज्वद्भावेभ्यो नुट्‌ पूर्वविप्रतिषेधेन (वा ४३७४) से बाध होता है ।
1 - वारि+आम्
अनन्तरं -
ह्रस्वनद्यापो नुट्‌ (७.१.५४) :
yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - वारि+नाम्
इति दर्शनीयम्।

**Comment by drdhaval2785** [comment]
Difficult to implement.
Not wrong.
It is only about preference about display.
So, closing the issue
