### ISSUE TITLE
अनादि + टा

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#69]
अनादिना इति एकमेव रूपं भवति। 
By iko'ci vibhaktau (7.1.73) :

इकोऽचि विभक्तौ (७.१.७३) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - अनादि+टा

2 - अनादि+ना

3 - अनादिन्+टा

इति सूत्रमत्र न प्रवर्तते।

**Comment by drdhaval2785** [comment]
If you choose bhASitapuMska option, then this has application. 
If you choose no bhASitapuMska option, this doesn't come.

**Comment by mrudani** [comment]
सत्यम्।
