### ISSUE TITLE
सुलू + टा

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#72]
सुलू + टा इत्यवस्थायां पुंवद्भावे कृते ह्रस्वाभावः, ह्रस्वाभावे घिसंज्ञाभावः घिसंज्ञाभावे तन्निमित्तः ना आदेशः न भवति आङो नास्त्रियाम् इति सूत्रेण। अतः यणादेशे - सुल्वा इति।
पुंवद्भावाभावे ह्रस्वे नपुंसके प्रातिपदिकस्य इति सूत्रेण ह्रस्वे कृते सुलु + टा अधुना इको अचि विभक्तौ इति सूत्रं प्रबाध्य आङो नास्त्रियाम् इति ना आदेशः एव भवति सुलुना इति।

**Comment by drdhaval2785** [comment]
Seems corrected now.
Check and raise a new ticket if you get some wrong resuts
