### ISSUE TITLE
सुलू + ङसि, ङस्, ओस्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#74]
सुल्वः इति पुंवद्भावे, सुलुनः इति पुंवद्भावाभावे। सुल्वोः सुलुनोः इति ओसि।

**Comment by mrudani** [comment]
तथैव सप्तम्यैकवचने सुलुनि सुल्वि इति रूपद्वयम्।

**Comment by drdhaval2785** [comment]
![capture](https://cloud.githubusercontent.com/assets/5755132/7785114/1b63f946-019f-11e5-8d83-655e0fa51c10.PNG)
When this is chosen, the forms get properly formed.
