### ISSUE TITLE
भाषितपुंस्कम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#76]
तृतीयादिषु भाषितपुंस्कमित्यादि सूत्रेण विधीयमानः पुंवद्भावः विकल्पेन भवति अतः तत्सूत्रप्रवृत्तिदर्शने रूपद्वयं दर्शनीयम्।

**Comment by drdhaval2785** [comment]
This rule is not mandating any vidhi. It only says that the next rules would apply optionally.
Therefore, not possible to show two identical forms.
