### ISSUE TITLE
प्रियक्रोष्टुशब्दः

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#77]
प्रयक्रोष्टुशब्दरूपाणि पञ्चम्येकवचनपर्यन्तमेवायान्ति। कः क्लेशः स्यात्।

**Comment by drdhaval2785** [comment]
There seem to be no other issue in this other than large number of optional forms e.g. 56 forms for some vibhaktis.
Therefore, the user may have lost patience and aborted the output in between.
