### ISSUE TITLE
प्ररैशब्दरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#78]
प्ररैशब्दस्य भाषितपुंस्कं भवतीति बालमनोरमा। पुंवत्वपक्षे प्रराया इत्यादीनि रूपाणि भवन्ति।

**Comment by drdhaval2785** [comment]
I don't understand.
The bAlamanoramA says that it is 'pradyuvat'.
pradyu has pradyunA.
So prariNA is good. Why prarAyA?

**Comment by mrudani** [comment]
तृतीयादिषु भाषितपुंस्कं पुंवद्गालवस्य इति सूत्रेण पुंवद्भावो भवतीति बालमनोरमा - टादावचि पुंवत्त्वविकल्पः प्रद्युशब्दवत्। इति। तेन पुंवत्त्वे प्रराया इति भवति।
