### ISSUE TITLE
विश्ववाह् + शस्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#79]
विश्वऊह् + अरुँ
आद्गुणः इति गुणे प्राप्ते तं प्रवाध्य एत्येधत्यूठ्सु इति वृद्धिः भवति।
अस्यां प्रक्रियायां वृद्धिकरणात्परं न विभक्तौ तुस्माः इत्यादीनि सूत्राणि दर्शयामः यदि तर्हि कश्चन क्लेशः भवति वा इति संशयः।

**Comment by drdhaval2785** [comment]
klezaH syAt.
