### ISSUE TITLE
सुदिउ + भ्याम्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#80]
By zeSo ghyasakhi (1.4.7) :

शेषो घ्यसखि (१.४.७) :

1 - सुदिउ+भ्याम्
अत्र कथं घिसंज्ञा।

**Comment by drdhaval2785** [comment]
कथं न स्यात्‌ ?
उकारान्तत्वात्‌ सखिभिन्नत्वाच्च घिसंज्ञा भवेदिति मे मतिः ।

**Comment by mrudani** [comment]
वस्तुतः एषः उकारान्तः न अपि तु वकारान्तः।

**Comment by drdhaval2785** [comment]
परन्तु प्रक्रियादशायान्तूकारान्तत्वेन परिणमते । तथा स्थिते घिसंज्ञाया अवकाशः स्यान्न वा स्यादिति प्रश्नः ।

**Comment by mrudani** [comment]
स्थानिवददाशेनल्विधौ इति प्रवर्तते खलु।
