### ISSUE TITLE
चतुर्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#81]
चतुर् शब्दरूपाणां संज्ञा अथवा उपसर्जनीभूतः नास्ति इति चयनेन अपि प्रथमपुरुष एकवचनरूपं दर्शयति।
You entered: चतुर् + सुँ Go Back

arthavadadhAturapratyayaH prAtipadikam (1.2.45), kRttaddhitasamAsAzca (1.2.46), pratyayaH (3.1.1), parazca (3.1.2), GyAppradipadikAt (4.1.1), svaujasamauTCaSTAbhyAmbhisGebhyAmbhyasGasibhyAmbhyasGasosAmGyossup (4.1.2), vibhaktizca (1.4.104) and supaH (1.4.103) :

अर्थवदधातुरप्रत्ययः प्रातिपदिकम्‌ (१.२.४५), कृत्तद्धितसमासाश्च (१.२.४६), प्रत्ययः (३.१.१), परश्च (३.१.२), ङ्‍याप्प्रातिपदिकात्‌ (४.१.१), स्वौजसमौट्छष्टाभ्याम्भिस्ङेभ्याम्भ्यस्ङसिभ्याम्भ्यस्ङसोसाम्ङ्‍योस्सुप्‌ (४.१.२), विभक्तिश्च (१.४.१०४) तथा सुपः (१.४.१०३) :

1 - चतुर्+सुँ

dvyekayordvivacanaikavacane (1.4.22) :

द्व्येकयोर्द्विवचनैकवचने (१.४.२२) :

1 - चतुर्+सुँ

By suDanapuMsakasya (1.1.43) :

सुडनपुंसकस्य (१.१.४३) :

1 - चतुर्+सुँ

By caturanaDuhorAmudAttaH (7.1.98) :

चतुरनडुहोरामुदात्तः (७.१.९८) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - चतुआर्+सुँ

By upadeze'janunAsika it (1.3.2) :

उपदेशेऽजनुनासिक इत्‌ (१.३.२) :

1 - चतुआर्+सुँ

By tasya lopaH (1.3.9) :

तस्य लोपः (१.३.९) :

1 - चतुआर्+स्

By na vibhaktau tusmAH (1.3.4) :

न विभक्तौ तुस्माः (१.३.४) :

1 - चतुआर्+स्

By apRkta ekAlpratyayaH (1.2.41) :

अपृक्त एकाल्प्रत्ययः (१.२.४१) :

1 - चतुआर्+स्

By halGyAbbhyo dIrghAtsutisyapRktaM hal (6.1.68) :

हल्ङ्‍याब्भ्यो दीर्घात्सुतिस्यपृक्तं हल्‌ (६.१.६८) :

1 - चतुआर्+

By iko yaNaci (6.1.77) :

इको यणचि (६.१.७७) y:

1 - चत्वार्+

By kharavasAnayorvisarjanIyaH (8.3.15) :

खरवसानयोर्विसर्जनीयः (८.३.१५) :

1 - चत्वाः

By anaci ca (8.4.47):

अनचि च (८.४.४७):

Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)

द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।

1 - चत्वाः

2 - चत्त्वाः

N.B.: By triprabhRtiSu zAkaTAyanasya (8.4.50), the dvitva is optionally not done in cases where there are more than three hals appearing consecutively. e.g. indra - inndra.

त्रिप्रभृतिषु शाकटायनस्य (८.४.५०) - तीन या उससे ज्यादा हल्‌ अगर हो तब शाकटायन के मत में द्वित्व नहीं होता है ।

By yaNo mayo dve vAcye (may in paJcamI and yaN in SaSThI) (vA 5018):

यणो मयो द्वे वाच्ये (मय्‌ पञ्चमी तथा यण्‌ षष्ठी) (वा ५०१८) :

Please note: Wherever there is dvitva, it is optionally negated by sarvatra zAkalyasya. (8.4.51)

द्वित्व का सर्वत्र सर्वत्र शाकल्यस्य (८.४.५१) से पाक्षिक निषेध होता है ।

1 - चत्वाः

2 - चत्व्वाः

3 - चत्त्वाः

4 - चत्त्व्वाः

By khari ca (8.4.55) :

N.B. By khari ca (8.4.55), 'car' varNas give 'car' varNas only as their savarNa :

खरि च (८.४.५५) :

खरि च (८.४.५५) से चर्‌ वर्णों का सवर्ण चर्‌ ही रहता है ।

1 - चत्वाः

2 - चत्व्वाः

3 - चत्त्वाः

4 - चत्त्व्वाः

By halo yamAM yami lopaH (8.4.64) :

हलो यमां यमि लोपः (८.४.६४) :

1 - चत्वाः

2 - चत्व्वाः

3 - चत्त्वाः

4 - चत्त्व्वाः

Final forms are :

आखिरी रूप हैं :

1 - चत्वाः

2 - चत्व्वाः

3 - चत्त्वाः

4 - चत्त्व्वाः

इति।

**Comment by drdhaval2785** [comment]
न भवति
