### ISSUE TITLE
इदम् + ङे

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#88]
By sarvanAmnaH smai (7.1.14) :

सर्वनाम्नः स्मै (७.१.१४) :

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)

यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)

1 - इद+स्मै

अनाप्यकः इति सूत्रेण अन् आदेशे प्राप्ते सति तं प्रबाध्य नित्यत्वात् सर्वनाम्नः स्मै इति सूत्रेण स्मै आदेशः भवति इति दर्शनीयम्।

**Comment by drdhaval2785** [comment]
Difficult to show special message.
Leaving it.
