### ISSUE TITLE
इदम् शब्दस्य सम्बोधनरूपाणि

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#89]
त्यदादेः सम्बोधनं नास्तीत्युत्सर्गः। इति सिद्धान्तकौमुदी। अनेन इदम् शब्दस्यापि सम्बोधनरूपाणि न भवन्तीति स्पष्टम्।

**Comment by drdhaval2785** [comment]
अयमुत्सर्गः कुत्र विहितः ? 
त्यदादिषु इदंशब्दस्य गणना कृता वा ? त्यदादीनामः इत्यत्र तु त्यदादिषु द्विपर्यन्तानामेवेष्टिः स्थिता । स्पष्टीकरोतु भवती ।

**Comment by drdhaval2785** [comment]
बालमनोरमामते तु प्रायिकमिदम्‌ । अन्यथा भाष्यप्रयोगविरोधस्स्यात्‌ ।

**Comment by mrudani** [comment]
बालामनोरमामते इति न उत्सर्गः इत्यस्य प्रायिकमिति अर्थः इति नदति बालमनोपमाकारः। सत्यम्, भाष्यविरोधादेव सम्बोधनरूपमङ्गीकार्यम्।
