### ISSUE TITLE
वृत्रहन्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#95]
000 इति दर्शयति। यथा -

yasmAtpratyayavidhistadAdi pratyaye'Ggam (2.4.13) and aGgasya (6.4.1)
यस्मात्प्रत्ययविधिस्तदादि प्रत्ययेऽङ्गम्‌ (२.४.१३) तथा अङ्गस्य (६.४.१)
1 - वृत्रहान्+सुँ
000

**Comment by mrudani** [comment]
अर्यमन्, पूषन् इत्येतयोश्शब्दयोः अपि 000 इति दर्शयति, अङ्गसंज्ञासन्दर्भे।

**Comment by drdhaval2785** [comment]
It was a debugging echo.
Removed now
