### ISSUE TITLE
मघवन्

### ISSUE THREAD

**Issue by mrudani** [drdhaval2785/SanskritSubanta#97]
मघवन् शब्दस्य तृ आदेशे तत्रलिद्यमान-ऋकारस्य इत्संज्ञायां तस्य लोपः क्रियते, परमत्र युगपदेव विभक्तिस्थप्रातिपदिकस्थयोर्वर्णयोः इत्संज्ञा तथा लोपश्च उच्यमानमस्ति। पृथगेव कुर्यात्।
By upadeze'janunAsika it (1.3.2) :
उपदेशेऽजनुनासिक इत्‌ (१.३.२) :
1 - मघवन्+सुँ
2 - मघवतृँ+सुँ
By tasya lopaH (1.3.9) :
तस्य लोपः (१.३.९) :
1 - मघवन्+स्
2 - मघवत्+स्

**Comment by drdhaval2785** [comment]
Difficult.
It doesn't seem to be a major issue. 
It would add two more steps - one for prakRti and one for pratyaya.
Leaving right now as it is
